server:
  port: 9090 # 端口

spring:
  application:
    name: order-service # 应用名称
  # 配置 Nacos 注册中心
  cloud:
    nacos:
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现，设置为 false 即可
        # server-addr: 127.0.0.1:8848 # Nacos 服务器地址，单机版
        # server-addr: 192.168.10.101:8848,192.168.10.102:8848,192.168.10.103:8848 # Nacos 服务器地址，集群版直连 ip 模式
        server-addr: 192.168.10.100:80 # Nacos 服务器地址，集群版 Nginx 转发
